services:
  recipe_keeper:
    build: .
    ports:
      - "8000:8000"
    environment:
      ROCKET_ENV: "production"
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "8000"
      DATABASE_URL: "sqlite:/app/data/RecipeKeeper.db3?mode=rwc" # Update with path to your db file inside the container
    volumes:
      - ./data:/app/data # Mount ./data directory on the host to /app/data in the container
    restart: unless-stopped
