services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ENV=production
    volumes:
      - ./RecipeKeeper.db3:/app/RecipeKeeper.db3 # Mount the SQLite file at the root of the project
    restart: unless-stopped
