name: Release

on:
  push:
    tags:
      - "v*" # Runs when a tag starting with "v" is pushed

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper libsqlite3-dev

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Rust and Frontend
        run: cargo build --release
        working-directory: ./ # Ensure we are building the Rust project from the root directory

      - name: Create platform-specific folder
        run: |
          PLATFORM="ubuntu-24.04-amd64"
          mkdir -p "release/$PLATFORM"
          cp target/release/recipe_keeper "release/$PLATFORM/"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: recipe_keeper
          path: release/ubuntu-24.04-amd64/recipe_keeper

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/ubuntu-24.04-amd64/recipe_keeper
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
