name: Release

on:
  push:
    tags:
      - "v*" # Runs when a tag starting with "v" is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper libsqlite3-dev

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install Node.js Dependencies
        run: npm install
        working-directory: ./client # Ensure we are installing dependencies in the client folder

      - name: Build Rust and Frontend
        run: cargo build --release
        working-directory: ./ # Ensure we are building the Rust project from the root directory

      - name: Create Platform Folder
        run: |
          # Automatically detect the platform and architecture
          PLATFORM="${RUNNER_OS}-${RUNNER_ARCH}"
          mkdir -p "release/$PLATFORM"

      - name: Move Binary to Platform Folder
        run: |
          # Move the built binary to the platform-specific folder
          PLATFORM="${RUNNER_OS}-${RUNNER_ARCH}"
          cp target/release/recipe_keeper "release/$PLATFORM/recipe_keeper"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: recipe_keeper
          path: release/ # Upload the whole release folder for easier access

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/${RUNNER_OS}-${RUNNER_ARCH}/recipe_keeper
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
